In [8]:
import numpy as np 

# this is 1d array and np.int reprents the size
myarr=np.array([2,3,4,5],np.int64)
myarr
myarr[1]

3

In [14]:
# this is 2d array 
myarr2d=np.array([[2,3,4,5,6,7,5]],np.int64)
myarr2d
myarr2d[0,3]

5

In [15]:
myarr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
myarr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
myarr2D.shape


(3, 3)

In [18]:
myarr2D.dtype

dtype('int32')

In [20]:
myarr2D[0,2]

3

In [21]:
myarr2D[0,2]=45
myarr2D

array([[ 1,  2, 45],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [22]:
myarr2D.size


9

In [23]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
# np.linspace(start,end,no of element)
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
# creates empty array with randon values
emp=np.empty((4,6))
emp

array([[4.67296746e-307, 1.69121096e-306, 1.60219442e-306,
        7.56587585e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 9.45697982e-308],
       [1.33511562e-306, 8.90103560e-307, 1.42410974e-306,
        1.00132228e-307, 1.33511018e-306, 1.69119330e-306]])

In [34]:
# to craete a empty array of preciously declared array
emp_like=np.empty_like(myarr)
emp_like

array([2, 3, 4, 5], dtype=int64)

In [35]:
# to create a identy matric
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr=arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr1=arr.ravel()
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr1.shape

(99,)

In [41]:
x= [[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ar.sum(axis=0)


array([12, 15, 18])

In [43]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [44]:
# transpose
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
# makes array linear
ar.flat
for item in ar.flat:
    print(item)


1
2
3
4
5
6
7
8
9


In [48]:
ar.ndim

2

In [49]:
ar.nbytes

36

In [57]:
oned=np.array([1,2,3,4,2,4,8,9])
max=oned.argmax()
max


7

In [58]:
min=oned.argmin()
min

0

In [59]:
oned.argsort()

array([0, 1, 4, 2, 3, 5, 6, 7], dtype=int64)

In [60]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
ar2=np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])


In [63]:
ar+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  8, 18]])

In [64]:
ar*ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  0, 81]])

In [66]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.where(ar2>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 2], dtype=int64))